import numpy as np
import h5py
import os
import warnings

import surfinBH

# Ignore this specific warning.
warnings.filterwarnings("ignore", message="Parameter x[[0-9]+] outside"
        " training range.")

# set global tolerances for floating point comparisons
atol = 0.0
rtol = 1.e-11

def test_fit_regression():
    """ Compares all existing fits against saved regression data.
        Regression data should already have been generated by
        generate_regression_data.py
    """
    # List of all available fits
    fit_names = surfinBH.fits_collection.keys()
    for name in fit_names:
        short_name = name.split('surfinBH')[-1]

        # Download fit data if needed
        if not os.path.isfile('%s/fit_%s.h5'%(surfinBH._dataPath.DataPath(),
                short_name)):

            surfinBH.DownloadData(name)


        # Load fit
        fit = surfinBH.LoadFits(name)

        # Load regression data
        regression_h5file = h5py.File('test/regression_data/fit_%s.h5'%(
                short_name))

        # Compare fit and regression data for each regression test
        test_keys = regression_h5file.keys()
        for test in test_keys:
            print '... running %s'%test
            test_h5grp = regression_h5file[test]
            x = test_h5grp['x'].value
            fit_keys = test_h5grp['y'].keys()
            for key in fit_keys:
                print '...... testing %s'%key
                y_reg = test_h5grp['y/%s'%key].value
                y_fit = fit(key, x)
                np.testing.assert_allclose(y_reg, y_fit, rtol=rtol, atol=atol)

        regression_h5file.close()

